import type { BuildFormData } from "../types";

export function makeFormData(
    overrides: Partial<BuildFormData> = {},
): BuildFormData {
    return {
        default_vault_addr: "",
        default_auth_method: "",
        default_vault_provider: "",
        default_mount_point: "",
        default_auth_role: "",
        default_auth_mount: "",
        default_policy_path: "",
        default_mapping_config: "",
        default_audit_log: "",
        default_allowed_pids: "",
        default_allowed_uids: "",
        default_debug: false,
        default_monitor: false,
        default_access_control: false,
        disable_cli_flags: false,
        default_log_file: "",
        default_log_max_size: "",
        default_log_max_backups: "",
        default_log_max_age: "",
        default_log_compress: "",
        default_ldap_username: "",
        default_ldap_password: "",
        default_vault_token: "",
        embed_policy_from_url: false,
        embed_policy_files: false,
        version: "",
        build_tag: "",
        target_os: "windows",
        target_arch: "amd64",
        source_dir: "",
        work_dir: "",
        output_dir: "",
        output_filename: "",
        code_signing_enabled: "false",
        certificate_path: "",
        certificate_password: "",
        ...overrides,
    };
}
